### PR TITLE
:robot: Add gowitness.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/446 :rocket:

### CODE REVIEW

**Comment by Menn1s** [comment]
Should there be a shortcut for this? Show help and drop into the appropriate directory. Doesn't show up in Information Gathering dir for me

**Comment by nos3curity** [comment]
@Menn1s it should show up under Recon. Lmk if the shortcut is there and works.

**Comment by Menn1s** [comment]
Oh I see it. Do you know how to change the "start in" dir? Doesn't change to a directory where gowitness is, but it does give me the help function

**Comment by nos3curity** [comment]
Tracked the issue down to a function in `common.vm`. Made a PR to fix. The package isn't blocked by the fix, so we can merge if there are no other issues @Menn1s

**Review by Menn1s — APPROVED** [review]
Nicee

**Pull request merged**
