### PR TITLE
:robot: Add yara.vm

### LINKED ISSUE #154: Package proposal: yara.vm
### Package Name

yara

### Tool Name

yara

### Package type

SINGLE_EXE

### Tool's version number

4.2.3

### Category

Forensic

### Tool's authors

Victor M. Alvarez, others

### Tool's description

The pattern matching swiss knife

### Download URL

https://github.com/VirusTotal/yara/releases/download/v4.2.3/yara-4.2.3-2029-win64.zip

### Download SHA256 Hash

a71a7070bc6dd392e0c066a590d2262382b0c3d73e76cc0851dc33ab5d51d381

### Why is this tool a good addition?

This is an open source industry standard tool for matching patterns in files and memory. It would be useful for testing YARA rules against live malware infections in memory.

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/154 :rocket:

Closes #154

### CODE REVIEW

**Comment by MalwareMechanic** [comment]
I'd vote for metapackage as long as the community package is up to date / has a history of being maintained. However, we'll likely still need to further tweak the metapackage, but that's okay

**Comment by MalwareMechanic** [comment]
Don't think I rebased this correctly, whoops -- but I only added files related to yara

**Review by mr-tz — APPROVED** [review]
nice, thanks

**Comment by mr-tz** [comment]
Should be fine with squash and merge.

Maybe related: What I just learned recently is that if you rebase, you need to specify exactly the number of commits you want to change (not more, otherwise, those commit hashes get changed as well).

**Comment by seanthegeek** [comment]
One small thing. I'd prefer if the exes were named yarac.exe and yara.exe, even though those are the filenames in the 64 bit Windows build, because the 64 bit CLI on every other platform does not include 64 in the name.

**Comment by MalwareMechanic** [comment]
@seanthegeek I've used the Chocolatey shims named "yara" and "yarac", let me know if that works for your needs and we can update as needed 😄

**Pull request merged**
