### PR TITLE
Add Dissect Python3 package

### PR DESCRIPTION
**Pull request by Schamper**
This change adds the Dissect Python package. Dissect is a framework consisting of multiple libraries and tools to interact with things like disk images and virtual machine disks.

More information:
https://docs.dissect.tools/en/latest/
https://github.com/fox-it/dissect

### CODE REVIEW

**Review by mr-tz — APPROVED** [review]

**Review by MalwareMechanic — CHANGES_REQUESTED** [review]
Please update the nuspec version number for this metapackage. Metapackages use the version format `0.0.0.YYYYMMDD`, so `0.0.0.20221203` should become `0.0.0.20230118`. See https://github.com/mandiant/VM-Packages/wiki/Package-Structure#version for more info.

**Comment by MalwareMechanic** [comment]
@mr-tz is this similar to #212?

**Comment by mr-tz** [comment]
Hm, yeah. Good catch. Still haven't really looked into what's going wrong in the lint for not catching this.

**Comment by Schamper** [comment]
@MalwareMechanic, apologies, missed that! Should be good now.

**Comment by MalwareMechanic** [comment]
@Schamper No worries, thanks for the contribution! ❤️

**Comment by mr-tz** [comment]
Yes, thank you!

**Pull request merged**
