### PR TITLE
Add AzureHound

### PR DESCRIPTION
**Pull request by nos3curity**
azurehound is the azure collector for bloodhound

this PR is blocked until #269 is resolved

### CODE REVIEW

**Comment by day1player** [comment]
Version 2.0.1 was released 3 hours ago -_-

**Comment by mr-tz** [comment]
If this is a standard GitHub install our auto-updates can fix this :)

**Review by Ana06 — COMMENTED** [review]
I don't know much about Azure, but aren't we missing dependencies here as it happens with https://github.com/mandiant/VM-Packages/pull/277? 🤔 

As @mr-tz says, the [automatic updates GH](https://github.com/mandiant/VM-Packages/blob/main/.github/workflows/update_package.yml) will updates the GH release after the PR is merged. We run it automatically once a week. 😄

**Comment by day1player** [comment]
Since this is a compiled release there should be no dependencies @Ana06

**Comment by nos3curity** [comment]
@day1player @Ana06 confirmed, no dependencies here. It's a compiled binary, not a Python tool like #278

**Pull request merged**
