### PR TITLE
:robot: Add scylla.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/167 :rocket:

### CODE REVIEW

**Comment by mr-tz** [comment]
RAR contents:
```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2015-05-03 14:00:14 ....A       434096        53682  Scylla_x64.map
2015-05-03 14:00:05 ....A         5298          981  Scylla_x64.lib
2015-05-03 13:59:11 ....A       473600       190236  Scylla_x86.dll
2015-05-03 13:59:11 ....A       468480       188607  Scylla_x86.exe
2015-05-03 13:59:10 ....A       472502        60031  Scylla_x86.map
2015-05-03 13:59:03 ....A         5184          958  Scylla_x86.lib
2014-02-04 16:01:25 ....A          447          281  Scylla.ini
2014-01-11 18:31:16 ....A         5895         1123  Scylla_Exports.txt
2011-09-07 18:11:42 ....A        35328        15599  Plugins/ImpRec_Plugins/Imprec_Wrapper_DLL.dll
2007-01-18 16:24:29 ....A         1556          521  Plugins/ImpRec_Plugins/PECompact 2.7.x.dll
2011-08-27 22:17:32 ....A         1449          700  Plugins/Include_Headers/ScyllaPlugin.h
2011-08-28 16:41:37 ....A        33792        15372  Plugins/PECompact.dll
2011-08-28 15:40:27 ....A        41472        18061  Plugins/PESpin_x64_v1.dll
2014-05-07 19:28:44 ....A        11776         5013  Plugins/ScyllaToImprecTree.exe
2011-09-07 18:13:08 ....A         8932         2717  Plugins/Sources/Imprec_Wrapper_DLL.cpp
2011-08-28 14:19:38 ....A         4304         1768  Plugins/Sources/PECompact.cpp
2011-08-28 15:40:25 ....A        13203         3919  Plugins/Sources/PESpin_x64_v1.cpp
2014-06-29 15:44:23 ....A        10596         9005  Plugins/Sources/scyllatoimprectree.rar
2015-05-03 14:01:06 ....A         5199         2276  Scylla_README.txt
2015-05-03 14:00:14 ....A       519680       204764  Scylla_x64.dll
2015-05-03 14:00:14 ....A       512000       202417  Scylla_x64.exe
2012-07-10 13:58:29 D....            0            0  Plugins/ImpRec_Plugins
2012-07-10 13:58:29 D....            0            0  Plugins/Include_Headers
2014-06-29 15:44:29 D....            0            0  Plugins/Sources
2014-06-29 15:40:51 D....            0            0  Plugins
------------------- ----- ------------ ------------  ------------------------
2015-05-03 14:01:06            3064789       978031  21 files, 4 folders
```

**Comment by Ana06** [comment]
@mr-tz what is the state of this PR?

**Comment by mr-tz** [comment]
Draft 😄 

I haven't looked into this further, the RAR contains the files and needs to be handled.

**Comment by Ana06** [comment]
Closing due to inactivity.

**Pull request closed without merging**
