### PR TITLE
fix: use category Networking

### PR DESCRIPTION
**Pull request by mr-tz**

### CODE REVIEW

**Comment by MalwareMechanic** [comment]
@mr-tz Make sure to bump the versions... when does that get caught? Was a test supposed to fail?

**Review by MalwareMechanic — CHANGES_REQUESTED** [review]
Increase the version in the `.nuspec` file plz

**Comment by mr-tz** [comment]
oh yeah, the linter failed to fail this... investigating

**Comment by mr-tz** [comment]
not sure what the linter bug was, but I renamed the file

**Review by MalwareMechanic — APPROVED** [review]

**Review by Ana06 — APPROVED** [review]

**Pull request merged**
