### PR TITLE
:robot: Add internal-monologue.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/592 :rocket:

### CODE REVIEW

**Comment by Ana06** [comment]
@nos3curity issue with CLA fixed, should we merge this PR?

**Comment by Ana06** [comment]
@mandiant/commando-vm :eyes:

**Comment by geo-lit** [comment]
@Ana06 LGTM. Category checked to be Credential Access

**Comment by Ana06** [comment]
`VM-Install-From-Github` has been replaced by`VM-Install-From-Zip` in https://github.com/mandiant/VM-Packages/pull/988 @emtuls will fix this PR :smile:

**Comment by emtuls** [comment]
Good to go @Ana06 !

**Pull request merged**
