### PR TITLE
Fix PR from JSON with special characters

### LINKED ISSUE #67: CI: send PR fails with "line 16: unexpected EOF while looking for matching `"'"
### What's the problem?

See https://github.com/mandiant/VM-Packages/runs/8303111845?check_suite_focus=true#step:5:20

May be an issue with the line breaks?

### Steps to Reproduce

add `send PR` label to METAPACKAGE issue

### Environment

CI

### Detected by test suite

No

### PR DESCRIPTION
**Pull request by mr-tz**
remove tmp json file after use and closes #67 
see example success run at https://github.com/mr-tz/VM-Packages/actions/runs/3052783651/jobs/4922573479

I think the issue was in the `system` call. There may still be a security issue here potentially running user input directly, but it's mitigated via the ENV usage and passing the arguments to the script now.

### CODE REVIEW

**Review by Ana06 — COMMENTED** [review]
> see example success run at https://github.com/mr-tz/VM-Packages/actions/runs/3052783651/jobs/4922573479

The run actually fails, but it seems it is because it doesn't have permissions to create the PR, #67 appears to be fixed 🎉 thanks for testing it @mr-tz! 💘 🎉 

---

> I think the issue was in the system call. There may still be a security issue here potentially running user input directly, but it's mitigated via the ENV usage and passing the arguments to the script now.

I don't know what you mean. Can you please elaborate?

---
Screen Shot 2022-09-14 at 18 21 39
@mr-tz is it ok for you if we merge this with `squash and merge`? Otherwise can you please rewrite this commit message? It seems you kept some old commit messages while rebasing.

**Comment by mr-tz** [comment]
There may have been potential for command injections (which the error with the `'` also indicated).
Can you review and squash and merge, please?

**Comment by Ana06** [comment]
> There may have been potential for command injections (which the error with the ' also indicated).

Right, good thing to take into account! Note that only people with permissions to add labels to issues can trigger this action.

**Comment by mr-tz** [comment]
Thank you!

> Note that only people with permissions to add labels to issues can trigger this action.

Yes, that's good.

**Pull request merged**
