### PR TITLE
:robot: Add powermad.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/510 :rocket:

### CODE REVIEW

**Review by Ana06 — COMMENTED** [review]
Can you please squash the commits or use "Squash and merge" when merging?

**Comment by nos3curity** [comment]
@Menn1s, @day1player, @skollr34p3r please review

**Comment by Menn1s** [comment]
Reviewing

**Review by Menn1s — APPROVED** [review]
Looks good

**Pull request merged**
