### PR TITLE
:robot: Add egress-assess.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/593 :rocket:

### CODE REVIEW

**Comment by Ana06** [comment]
@nos3curity issue with CLA fixed, should we merge this PR?

**Comment by Ana06** [comment]
@nos3curity 👀

**Comment by day1player** [comment]
tagging @Menn1s and @geo-lit as @skollr34p3r is stepping away from the project :)

**Comment by Ana06** [comment]
`VM-Install-From-Github` has been replaced by`VM-Install-From-Zip` in https://github.com/mandiant/VM-Packages/pull/988 @emtuls will fix this PR :smile:

**Comment by emtuls** [comment]
Good to go @Ana06 !

**Review by Ana06 — APPROVED** [review]

**Pull request merged**
