### PR TITLE
:robot: Add dependencywalker.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/155 :rocket:

### CODE REVIEW

**Comment by mr-tz** [comment]
Use metapackage via https://community.chocolatey.org/packages/dependencywalker instead?

**Comment by Ana06** [comment]
I thin when possible we should use the community package. We should document this and make it clear it in the issues templates.

**Comment by MalwareMechanic** [comment]
I also vote for community packages when possible as long as they are up to date and maintained

**Comment by MalwareMechanic** [comment]
The community package uses a HTTP URL instead of an HTTPS URL. Until that gets updated, I suggest we maintain the link ourselves.

Screen Shot 2022-12-09 at 14 06 37

I kept getting error as well. My guess is since it's HTTP there's some network device blocking it for me.
Screen Shot 2022-12-09 at 14 08 14

**Comment by MalwareMechanic** [comment]
Ha, nevermind. Seems the website is down at the moment. I'll assess this once it's back up.

Screen Shot 2022-12-09 at 14 15 37

**Review by mr-tz — APPROVED** [review]

**Pull request merged**
