### PR TITLE
:robot: Add adconnectdump.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/494 :rocket:

### CODE REVIEW

**Comment by nos3curity** [comment]
FYI, not adding a shortcut for this tool, because it is meant to be run on the target machine, not on the CommandoVM

**Comment by nos3curity** [comment]
Some of the scripts inside the repo use python2, but we are interested in ADSyncDecrypt and the other apps here, which are all dotnet and are meant to be executed on the remote target machine.

**Comment by nos3curity** [comment]
@Menn1s, @day1player, @skollr34p3r please review

**Review by skollr34p3r — APPROVED** [review]
GTG

**Pull request merged**
