### PR TITLE
Feat/add dependabot

### PR DESCRIPTION
**Pull request by MalwareMechanic**
Seems like dependabot can auto-update our nuget dependencies for us. Not sure how to test this before a commit to main, so if anyone know please let me know. I've briefly read up on dependabot on https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

### CODE REVIEW

**Comment by mr-tz** [comment]
I'm not sure this really does what we want, but let's try... To test, you can enable dependabot in your fork.

**Review by mr-tz — APPROVED** [review]

**Comment by Ana06** [comment]
I am not sure which dependencies you are trying to update.

I have used dependabot in other projects. For example, this PR was sended by dependabot https://github.com/Ana06/get-changed-files/pull/22

You can test it by enabling it in a fork of the project.

**Comment by MalwareMechanic** [comment]
I noticed in the "Insights" tab, there was a section on left called "Dependency Graph". It looks like GitHub can parse the `.nuspec` files in our packages and determine the versions of the dependencies. I was hoping Dependabot could auto-update these on a daily basis to prevent issues like https://github.com/mandiant/VM-Packages/issues/148. I'll experiment further in my fork first 😄 

Screen Shot 2022-12-07 at 08 41 47
Screen Shot 2022-12-07 at 08 41 31

**Comment by MalwareMechanic** [comment]
Oh nice! Yep, looks like this is redundant -- my bad. Maybe we can increase the frequency for the updates to two times a week?

**Comment by MalwareMechanic** [comment]
Closing as we already have an updating solution in place

**Pull request closed without merging**
