### PR TITLE
Add python and jupyter vscode extension packages

### PR DESCRIPTION
**Pull request by d35ha**
Closes https://github.com/mandiant/VM-Packages/issues/1074.

### CODE REVIEW

**Review by emtuls — CHANGES_REQUESTED** [review]
I don't think we need to add all of these extensions separately. Just adding the `python extension` alone adds both `Pylance` and `Python Debugger` (https://marketplace.visualstudio.com/items?itemName=ms-python.python). :)

Also, I think we should name the packages `vscode.python.vm` and `vscode.jupyter.vm` instead, as the extension piece makes the name a bit longer than necessary.

Overall, they work great though! Just those changes and I think it'll be good to go.

**Comment by d35ha** [comment]
> Also, I think we should name the packages `vscode.python.vm` and `vscode.jupyter.vm` instead, as the extension piece makes the name a bit longer than necessary.

@emtuls 
Renaming it to `vscode.<ext>.vm` would make it harder to exclude these extensions at `lint.py` (see: https://github.com/mandiant/VM-Packages/blob/aca19f0dd7238dc8c9920de8e96a88cd5a285d15/scripts/test/lint.py#L322), also it's I think it's consistent with `notepadpp.plugin.<plugin>.vm` and `ida.plugin.<plugin>.vm`.

**Comment by d35ha** [comment]
@emtuls 
Updated.

**Review by Ana06 — APPROVED** [review]
Thanks for the work @d35ha and for the review @emtuls, LGTM!

**Review by emtuls — APPROVED** [review]
Looks good! Awesome job @d35ha, thank you!

**Pull request merged**
