### PR TITLE
Fix ArsenalImageMounter dependency

### PR DESCRIPTION
**Pull request by naacbin**
This fixes issue #852.

### CODE REVIEW

**Review by Ana06 — COMMENTED** [review]
Thanks @naacbin!

I have tested it locally and I get the following message:
Screenshot 2024-02-14 at 11 10 48


Is this also a missing dependency we need to add?

@mandiant/commando-vm can you please review this PR as well? I am not familiar with this tool 😅

**Comment by naacbin** [comment]
It is a missing dependency but I didn''t get the time before to investigate. There is 2 options to add this dependency avoiding this message :
- [DriverFiles.zip](https://github.com/ArsenalRecon/Arsenal-Image-Mounter/blob/master/DriverSetup/DriverFiles.zip) file contains a folder `DriverFiles\Win10\x64` with 6 drivers 5 have to be installed.
- Launch the application and click yes with autohotkey.

**Comment by Ana06** [comment]
@mandiant/commando-vm opinions?

**Comment by Ana06** [comment]
dotnet-6.vm is failing to install in our test suite because of Arsenal Image Mounter requiring a different version from dotnet-6.0-desktopruntime than the one in dotnet-6.vm. @naacbin do you know when you will have time to rebase (sorry I shouldn't have merged the update of this tool) and add the missing driver in this PR?

**Comment by naacbin** [comment]
> dotnet-6.vm is failing to install in our test suite because of Arsenal Image Mounter requiring a different version from dotnet-6.0-desktopruntime than the one in dotnet-6.vm. @naacbin do you know when you will have time to rebase (sorry I shouldn't have merged the update of this tool) and add the missing driver in this PR?

I will rebase today, but I don't know when I will have time to add the missing drivers. So, we should merge this PR as it's only one click for user to install drivers if needed. In the same time, we open an issue or add it to the existing one for the drivers dependency.

**Comment by Ana06** [comment]
@naacbin I think you have pushed the wrong changes.

It is ok for me to add the missing driver later. I have tracked it in https://github.com/mandiant/VM-Packages/issues/910

**Comment by naacbin** [comment]
> @naacbin I think you have pushed the wrong changes.
> 
> It is ok for me to add the missing driver later. I have tracked it in #910

Ahah, indeed it's fixed now

**Review by Ana06 — APPROVED** [review]

**Comment by Ana06** [comment]
Thanks @naacbin! :rocket:

**Pull request merged**
