### PR TITLE
:robot: Add snaffler.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/498 :rocket:

### CODE REVIEW

**Comment by skollr34p3r** [comment]
I'm not seeing the Tools folder shortcut on the Desktop and not seeing anywhere where the 'Reconnaissance' category gets added. The tool is only going to 'C:\Tools\Snaffler\Snaffler.exe' from what I can tell. Is this intentional?

**Comment by day1player** [comment]
> I'm not seeing the Tools folder shortcut on the Desktop and not seeing anywhere where the 'Reconnaissance' category gets added. The tool is only going to 'C:\Tools\Snaffler\Snaffler.exe' from what I can tell. Is this intentional?

Did you install this on a standard windows VM or on an already configured Commando/Flare VM? You might not be seeing it because the Tools folder and the variables for the shortcuts are configured during the install process

**Comment by skollr34p3r** [comment]
> > I'm not seeing the Tools folder shortcut on the Desktop and not seeing anywhere where the 'Reconnaissance' category gets added. The tool is only going to 'C:\Tools\Snaffler\Snaffler.exe' from what I can tell. Is this intentional?
> 
> Did you install this on a standard windows VM or on an already configured Commando/Flare VM? You might not be seeing it because the Tools folder and the variables for the shortcuts are configured during the install process

Standard. That's what I've been using the whole time. It's a standard win10 dev machine with choco just installed and snapshotted with the PS profile I like and a freshly git cloned mandiant/VM-Packages repo that I pull from before testing every time.

**Comment by nos3curity** [comment]
Unable to reproduce the issue @skollr34p3r. 

After digging into the `VM-Install-Shortcut` function in `common.vm`, i can see that the function asserts that the shortcut path exists, so if it failed for some reason, it would fail the entire package install, which isn't happening here. Something isn't right with your VM.

**Review by skollr34p3r — APPROVED** [review]
Looks solid to me!

**Pull request merged**
