### PR TITLE
:robot: Add situational-awareness-bofs.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/371 :rocket:

### CODE REVIEW

**Review by mr-tz — APPROVED** [review]

**Comment by day1player** [comment]
similar to #383 should we name this with the tool author? ie "trustedsec-situational-awareness-bof"

**Comment by nos3curity** [comment]
@day1player changed the tool category. I think #383 being "c2-collection" is too generic, needing us to specify whose collection it is, but in this case, it is specific and known enough under this name that it isn't necessary in my opinion. Thoughts?

**Comment by day1player** [comment]
Yeah I think you're right. I noticed the nuspec file is still titled with an "s", I think after that is fixed we are good to merge

**Comment by nos3curity** [comment]
@day1player fixed. Ready to merge.

**Pull request merged**
