### PR TITLE
:robot: Add mfasweep.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/491 :rocket:

### CODE REVIEW

**Comment by nos3curity** [comment]
thoughts on whether this belongs in credential access or recon?

**Review by Ana06 — COMMENTED** [review]
Can you please squash the commits or use "Squash and merge" when merging? We don't want to keep `fix` commits in order to have a clean commit history. I also recommend reading about commits good practices (Use imperative mood, capitalize the first word,  etc), for example:
- https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages
- https://about.gitlab.com/blog/2018/06/07/keeping-git-commit-history-clean/

**Comment by nos3curity** [comment]
@Menn1s, @day1player, @skollr34p3r please review

**Review by skollr34p3r — APPROVED** [review]
GTG

**Pull request merged**
