### PR TITLE
:robot: Add inveigh.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/500 :rocket:

### CODE REVIEW

**Comment by nos3curity** [comment]
I think this belongs in credential access, since we are trying to get a hold of NTLM hashes. Thoughts?

**Comment by nos3curity** [comment]
b@Menn1s, @day1player, @skollr34p3r please review

**Comment by Menn1s** [comment]
Reviewing

**Comment by nos3curity** [comment]
@Menn1s updated the arguments. Lmk if this works.

**Review by Menn1s — APPROVED** [review]
Noice and fixed

**Pull request merged**
