### PR TITLE
Adding HeidiSQL

### PR DESCRIPTION
**Pull request by skollr34p3r**

### CODE REVIEW

**Review by nos3curity — CHANGES_REQUESTED** [review]
Not sure I understand the install script. It looks like the nuspec file lists heidisql as a dependency, but the chocolateyInstall.ps1 does manual installation using a direct installer link. Additionally, the tool leaves a shortcut on the Desktop.

Is there something wrong with the dependency install that requires us to use the installer?

**Comment by skollr34p3r** [comment]
> Not sure I understand the install script. It looks like the nuspec file lists heidisql as a dependency, but the chocolateyInstall.ps1 does manual installation using a direct installer link. Additionally, the tool leaves a shortcut on the Desktop.
> 
> Is there something wrong with the dependency install that requires us to use the installer?

Taking a look now. This is one of the first packages I worked on, so it's likely there are some inefficiencies. I know it didn't leave a desktop shortcut when I last tested it, but regarding using an installer, I made this package before I understood how dependencies work with choco and our tooling

**Comment by skollr34p3r** [comment]
Turns out there's already a new version of this available in choco since I started on this package. Going to use new metapackage issue to create an update done. The link is here: https://github.com/mandiant/VM-Packages/pull/590

**Comment by Ana06** [comment]
@skollr34p3r what is the state of this PR?

**Comment by Ana06** [comment]
@skollr34p3r 👀

**Comment by day1player** [comment]
tagging @Menn1s and @geo-lit as @skollr34p3r is stepping away from the project :)

**Comment by geo-lit** [comment]
looks to be duplicate of #590

**Comment by Ana06** [comment]
Closing this PR to celebrate its 1 year birthday. @geo-lit please re-open it if it is still needed.

birthday

**Pull request closed without merging**
