### PR TITLE
:robot: Add heidisql.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/589 :rocket:

### CODE REVIEW

**Comment by skollr34p3r** [comment]
Uninstall is rough, but I got the install working correctly. @day1player @nos3curity @Menn1s give it a review and then once this is approved and merged, close out https://github.com/mandiant/VM-Packages/pull/320 as well since it's the same package

**Comment by nos3curity** [comment]
Need to add handling for ARM devices installing HeidiSQL to Program Files x86:
```
ERROR: Cannot find path 'C:\Program Files\HeidiSQL\heidisql.exe' because it does not exist.
The upgrade of heidisql.vm was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\heidisql.vm\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by Ana06** [comment]
What is the state of this PR?

**Comment by Ana06** [comment]
@nos3curity @skollr34p3r what is the state of this PR?

**Comment by day1player** [comment]
tagging @Menn1s and @geo-lit as @skollr34p3r is stepping away from the project :)

**Comment by geo-lit** [comment]
@Ana06 state is unknown. Will test in the coming week and try to fix

**Comment by Ana06** [comment]
@geo-lit any updates? :eyes:

**Comment by Ana06** [comment]
Closing this issue due to inactivity. @geo-lit re-open it or create a new one if you have time to work on it.

**Pull request closed without merging**
