### PR TITLE
:robot: Package update

### PR DESCRIPTION
**Pull request by vm-packages**
Automated package update

### CODE REVIEW

**Comment by Ana06** [comment]
The package update script should only update packages that pass the test, why is it adding in the PR packages that fail to update? 🤔

**Review by Ana06 — COMMENTED** [review]
I have removed some of the commits manually and tested the rest locally so that we can merge this PR as it fixes exiftool

**Comment by Ana06** [comment]
We didn't merge this fast enough and the bot overwrote my changes 😡 I'll push them again...

**Comment by day1player** [comment]
bad bot! bad!

**Review by Ana06 — APPROVED** [review]
I have removed some of the commits manually and tested the rest locally (AGAIN). Merging to avoid that the bots overwrites the changes AGAIN in few hours.

**Pull request merged**
