### PR TITLE
Add pdbresym.vm

### PR DESCRIPTION
**Pull request by Ana06**
Install PDBReSym and run `PDBReSym cachesyms` to iterate through `C:\Windows\System32` downloading all PDBs concurrently. The downloaded symbols are store into `C:\symbols`.

@stevemk14ebr and @schrodyn please take a look :wink: 

Closes https://github.com/mandiant/VM-Packages/issues/688

### CODE REVIEW

**Comment by stevemk14ebr** [comment]
Looks good to me! We may want to consider the VM size as these pdbs can be big, and some people may also want the wow64 32 bit system binaries cached as well (can be done easily with flags to the tool)

**Comment by Ana06** [comment]
@stevemk14ebr I agree. We are not planing to add it to the default config because of the increase in size, similar to Visual Studio.

**Comment by schrodyn** [comment]
Nice! This covers exactly what I wanted. Thank you both =)

**Comment by emtuls** [comment]
Should we also attempt to remove `C:\symbols` when uninstalling?

Also, should we have something that prints out something like `downloading all PDB's. This may take a few minutes...`? 
When I tested it, it was hard to tell if it was working or just taking a bit of time, and it doesn't natively spit out which PDB it's downloading or anything that indicates that it is running.

I think it also should include `<dependency id="common.vm" version="0.0.0.20240410" />` from https://github.com/mandiant/VM-Packages/pull/959. I had an older `common.vm` I think that was installed on my test setup and it failed until I updated my `common.vm` to latest.

**Comment by Ana06** [comment]
@emtuls 
> Should we also attempt to remove C:\symbols when uninstalling?

I don't think we should. We don't know if the user downloaded other things in there, so I would say better we keep it simple. There is the following comment in the code: `Uninstalling only removes the tool not the downloaded symbols`



I'll add that a debugging message and the common dependency, thanks for the review @emtuls!

**Comment by stevemk14ebr** [comment]
The tool does actually provide pretty extensive output. If it's not printing it's either due to the terminal you're using or a bug

**Comment by emtuls** [comment]
Definitely seems to be some sort of terminal/powershell issue.

Running it on its own seems to work fine (even in powershell console), but running it in the script does not. I tried a bunch of various combinations to try to get it to display, but nothing worked (docs says it writes to Stderr: https://docs.rs/indicatif/latest/indicatif/). 

Oh well. :(

**Comment by stevemk14ebr** [comment]
Looked into this for a second, stderr seems to be the preferred stream to write progress type information to, and also it's used for errors. This is so that progress type information can still get printed while stdout for final results can be easily readirected. 

I'm not sure which script you used to run it exactly, but perhaps the runner script should be adjusted to redirect output to the console for progress updates (maybe optionally) for some packages where the progress information is wanted to be displayed?

**Comment by Ana06** [comment]
@stevemk14ebr 

> Looked into this for a second, stderr seems to be the preferred stream to write progress type information to, and also it's used for errors. This is so that progress type information can still get printed while stdout for final results can be easily readirected.

We are not really interested in progress information when installing a package as this would makes the log difficult to read. I think an info message as @emtuls suggested is enough in this case.

**Review by emtuls — APPROVED** [review]

**Comment by stevemk14ebr** [comment]
@Ana06 I think this tool should always be present, but only executed in FULL configurations. As the installer file is written now it will execute the binary always, which makes it unnacceptable to add to the default config (so it will be missing from most FLAREVM builds). It being missing is bad, it should always be present, but not always run.

I'd suggest modifying the installer script to accept some kind of arguments that make it aware of the configration. And in the FULL configuration it will execute the binary. Is this possible?

**Pull request merged**
