### PR TITLE
fix: delete json file

### PR DESCRIPTION
**Pull request by mr-tz**
alternative to #71 deleting the file after usage

### CODE REVIEW

**Review by MalwareMechanic — APPROVED** [review]
Seems short and easy, I like it

**Comment by mr-tz** [comment]
Bummer we cannot really test it.

**Comment by mr-tz** [comment]
@Ana06 should we go with this (and test in production 😄)?

**Review by Ana06 — COMMENTED** [review]
Note this doesn't fix https://github.com/mandiant/VM-Packages/issues/67, we still need to manually escape `'`. So it is basically the same as https://github.com/mandiant/VM-Packages/pull/71. A fix for #67 would be the ideal solution, but if we don't have time for it now, we should merge #71 or #72 (no preference, they are the same).

**Comment by mr-tz** [comment]
superseded by #73

**Pull request closed without merging**
