### PR TITLE
:robot: Package update

### PR DESCRIPTION
**Pull request by vm-packages**
Automated package update

### CODE REVIEW

**Review by Ana06 — CHANGES_REQUESTED** [review]
I tested _some_ of the tools:
- cywin works
- imhex is missing a dependency/driver
image
- microsoft-windows-terminal.vm is broken, it seem not to install the tool. Not sure if it is caused by the update.
- notepad works
- pe-sieve works, but should be run as a console app (although it is not related with the update)

**Comment by emtuls** [comment]
@Ana06 It seems that `ImHex` requires a graphics card with OpenGL 3.0 support (at least that's what is stated on the github: https://github.com/WerWolv/ImHex). Not sure if you've got that enabled in your VM or not. There are builds labeled "NoGPU" that could be used instead, but the author stated that these builds might run a bit slower.

In it's current state, it does seem to work for on VMWare but it's also very weird looking...most of the interface is VERY transparent and hard to even see anything...

**Comment by emtuls** [comment]
So far, I've also tested:
- `cutter` works
- `hollowshunter` works
- `imhex` sort of works...
- `sliver` works
- `VSCode` works
- `microsoft-windows-terminal` does not work, but should be fixed when this is merged: https://github.com/mandiant/VM-Packages/pull/936

Not sure what we should do with `imhex`. The tool seems cool based on the Github Repo, just unfortunate that it looks weird on my system. Might be a driver issue in the VM.

**Comment by Ana06** [comment]
@emtuls 
> Not sure what we should do with imhex. The tool seems cool based on the Github Repo, just unfortunate that it looks weird on my system. Might be a driver issue in the VM.

Does this also happen to you before the update?

**Comment by Ana06** [comment]
I have removed microsoft-windows-terminal and imhex from this update so that we can merge it.
- microsoft-windows-terminal is fixed and updated in https://github.com/mandiant/VM-Packages/pull/936
- we need to discuss what to do with imhex @emtuls could you send and issue after confirming if the issue for you is the update or if the tool was already broken? We may need to fix the tool or remove it from flare-vm default configuration

@emtuls thanks for adding the missing dependency for cutter :+1:

**Review by Ana06 — APPROVED** [review]

**Pull request merged**
