### PR TITLE
:robot: Add minidump.vm

### PR DESCRIPTION
**Pull request by vm-packages**
Automated PR from https://github.com/mandiant/VM-Packages/issues/502 :rocket:

### CODE REVIEW

**Comment by nos3curity** [comment]
FYI, tool not meant to be run on Commando, but on the target machine, therefore no shortcut

**Comment by Ana06** [comment]
> tool not meant to be run on Commando, but on the target machine, therefore no shortcut

`VM-Install-Raw-GitHub-Repo` adds a shortcut: https://github.com/mandiant/VM-Packages/blob/86ad510c5d480476cdc79366ad8f029e218eac46/packages/common.vm/tools/vm.common/vm.common.psm1#L258C16-L258C16

**Comment by nos3curity** [comment]
@Ana06, sorry to clarify, intending no shortcut to the exe in the repo

**Comment by nos3curity** [comment]
@Menn1s, @day1player, @skollr34p3r please review

**Review by skollr34p3r — APPROVED** [review]
GTG

**Pull request merged**
